<a href="https://colab.research.google.com/github/analystnilava/pandas_quick_prac_/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [147]:
import pandas as pd

# chech the pandas version.

In [148]:
pd.__version__

'2.2.2'

#create the data frame

In [149]:
df = pd.DataFrame([10 , 20 ,30 , 40 , 50 , 60],columns =["col_name"])
df

   col_name
0        10
1        20
2        30
3        40
4        50
5        60

#CHECK THE TYPE

In [150]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

#CREATE DICTONARY

In [151]:
DATA = {
    "NANE" : ["NILAVA", "SNEHA" , "SANU" , "ABIR" , "SAYAN" , "POUSHALI"],
    "AGE" : [23 , 23 , 22 , 22 , 25 , 22],
    "SALARY" :[25000 , 30000, 25000 , 30000 , 35000 , 60000]
}
print(DATA)

{'NANE': ['NILAVA', 'SNEHA', 'SANU', 'ABIR', 'SAYAN', 'POUSHALI'], 'AGE': [23, 23, 22, 22, 25, 22], 'SALARY': [25000, 30000, 25000, 30000, 35000, 60000]}

#CONVART DICT TO DATAFRAME

In [152]:
df1 = pd.DataFrame(DATA)
df1

       NANE  AGE  SALARY
0    NILAVA   23   25000
1     SNEHA   23   30000
2      SANU   22   25000
3      ABIR   22   30000
4     SAYAN   25   35000
5  POUSHALI   22   60000

In [153]:
# basic dataframe understanding
df1.head(2)

     NANE  AGE  SALARY
0  NILAVA   23   25000
1   SNEHA   23   30000

In [154]:
df1.tail(2)

       NANE  AGE  SALARY
4     SAYAN   25   35000
5  POUSHALI   22   60000

In [155]:
df1.shape

(6, 3)

In [156]:
df1.columns

Index(['NANE', 'AGE', 'SALARY'], dtype='object')

#CHANGE COLUMN NAME

In [157]:
df1.rename(columns= {'NANE' : 'Full_NAME', 'AGE' : 'Age_in_Years'})

  Full_NAME  Age_in_Years  SALARY
0    NILAVA            23   25000
1     SNEHA            23   30000
2      SANU            22   25000
3      ABIR            22   30000
4     SAYAN            25   35000
5  POUSHALI            22   60000

In [158]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NANE    6 non-null      object
 1   AGE     6 non-null      int64
 2   SALARY  6 non-null      int64
dtypes: int64(2), object(1)
memory usage: 276.0+ bytes

In [159]:
df1.describe()

             AGE        SALARY
count   6.000000      6.000000
mean   22.833333  34166.666667
std     1.169045  13197.221930
min    22.000000  25000.000000
25%    22.000000  26250.000000
50%    22.500000  30000.000000
75%    23.000000  33750.000000
max    25.000000  60000.000000

In [160]:
df1.to_csv("test.csv", index=False)

In [161]:
df4 = pd.read_csv("test.csv")
df4

       NANE  AGE  SALARY
0    NILAVA   23   25000
1     SNEHA   23   30000
2      SANU   22   25000
3      ABIR   22   30000
4     SAYAN   25   35000
5  POUSHALI   22   60000

# COLUMN selection

In [162]:
df4["NANE"] # single row selection

0      NILAVA
1       SNEHA
2        SANU
3        ABIR
4       SAYAN
5    POUSHALI
Name: NANE, dtype: object

In [163]:
from ast import Index
df4[["NANE" , "AGE"]]

       NANE  AGE
0    NILAVA   23
1     SNEHA   23
2      SANU   22
3      ABIR   22
4     SAYAN   25
5  POUSHALI   22

#ROW selection

In [164]:
df4.loc[(df4.NANE == "SNEHA") & (df4.SALARY > 25000)]

    NANE  AGE  SALARY
1  SNEHA   23   30000

In [165]:
df4.loc[df4.NANE == "SANU"]

   NANE  AGE  SALARY
2  SANU   22   25000

In [166]:
df4.loc[0:2]

     NANE  AGE  SALARY
0  NILAVA   23   25000
1   SNEHA   23   30000
2    SANU   22   25000

#iloc (0 to n-1)

In [167]:
df4.iloc[0:2]

     NANE  AGE  SALARY
0  NILAVA   23   25000
1   SNEHA   23   30000

# FILTER

In [168]:
df4['AGE']>22

0     True
1     True
2    False
3    False
4     True
5    False
Name: AGE, dtype: bool

In [169]:
df4[df4['AGE']>22]

     NANE  AGE  SALARY
0  NILAVA   23   25000
1   SNEHA   23   30000
4   SAYAN   25   35000

In [170]:
df4[(df4['AGE']>22) & (df4['SALARY']>25000)]

    NANE  AGE  SALARY
1  SNEHA   23   30000
4  SAYAN   25   35000

#use filter using where

In [171]:
df4.where((df4['AGE']>22) & (df4['SALARY']>25000) , other ="not elgible")

          NANE          AGE       SALARY
0  not elgible  not elgible  not elgible
1        SNEHA           23        30000
2  not elgible  not elgible  not elgible
3  not elgible  not elgible  not elgible
4        SAYAN           25        35000
5  not elgible  not elgible  not elgible

#row and col operation(update , add , delete)

In [172]:
df4['GENDER']=(["MALE" , "FEMALE" , "MALE" , "MALE" ,"MALE", "FEMALE"] )

In [173]:
df4

       NANE  AGE  SALARY  GENDER
0    NILAVA   23   25000    MALE
1     SNEHA   23   30000  FEMALE
2      SANU   22   25000    MALE
3      ABIR   22   30000    MALE
4     SAYAN   25   35000    MALE
5  POUSHALI   22   60000  FEMALE

In [174]:
df4['Bonous'] = (df4.SALARY)*0.20

In [175]:
df4

       NANE  AGE  SALARY  GENDER   Bonous
0    NILAVA   23   25000    MALE   5000.0
1     SNEHA   23   30000  FEMALE   6000.0
2      SANU   22   25000    MALE   5000.0
3      ABIR   22   30000    MALE   6000.0
4     SAYAN   25   35000    MALE   7000.0
5  POUSHALI   22   60000  FEMALE  12000.0

In [176]:
# ADD NEW ROWS
df4.loc[len(df)]=['BIDYUT' , 65 , 100000,'MALE' ,20000]

In [177]:
df4

       NANE  AGE  SALARY  GENDER   Bonous
0    NILAVA   23   25000    MALE   5000.0
1     SNEHA   23   30000  FEMALE   6000.0
2      SANU   22   25000    MALE   5000.0
3      ABIR   22   30000    MALE   6000.0
4     SAYAN   25   35000    MALE   7000.0
5  POUSHALI   22   60000  FEMALE  12000.0
6    BIDYUT   65  100000    MALE  20000.0

In [178]:
# update value using index
df4.loc[0 , 'SALARY'] = 90000

In [179]:
df4

       NANE  AGE  SALARY  GENDER   Bonous
0    NILAVA   23   90000    MALE   5000.0
1     SNEHA   23   30000  FEMALE   6000.0
2      SANU   22   25000    MALE   5000.0
3      ABIR   22   30000    MALE   6000.0
4     SAYAN   25   35000    MALE   7000.0
5  POUSHALI   22   60000  FEMALE  12000.0
6    BIDYUT   65  100000    MALE  20000.0

In [180]:
df4.drop('Bonous' , axis=1)

       NANE  AGE  SALARY  GENDER
0    NILAVA   23   90000    MALE
1     SNEHA   23   30000  FEMALE
2      SANU   22   25000    MALE
3      ABIR   22   30000    MALE
4     SAYAN   25   35000    MALE
5  POUSHALI   22   60000  FEMALE
6    BIDYUT   65  100000    MALE

In [181]:
df4.drop(df4[df4['NANE']=='SAYAN'].index , axis=0 , inplace=True)

In [182]:
df4

       NANE  AGE  SALARY  GENDER   Bonous
0    NILAVA   23   90000    MALE   5000.0
1     SNEHA   23   30000  FEMALE   6000.0
2      SANU   22   25000    MALE   5000.0
3      ABIR   22   30000    MALE   6000.0
5  POUSHALI   22   60000  FEMALE  12000.0
6    BIDYUT   65  100000    MALE  20000.0

#sort value

In [183]:
df4.sort_values('SALARY')

       NANE  AGE  SALARY  GENDER   Bonous
2      SANU   22   25000    MALE   5000.0
1     SNEHA   23   30000  FEMALE   6000.0
3      ABIR   22   30000    MALE   6000.0
5  POUSHALI   22   60000  FEMALE  12000.0
0    NILAVA   23   90000    MALE   5000.0
6    BIDYUT   65  100000    MALE  20000.0

In [184]:
# in desecding order
df4.sort_values('SALARY' , ascending= False)

       NANE  AGE  SALARY  GENDER   Bonous
6    BIDYUT   65  100000    MALE  20000.0
0    NILAVA   23   90000    MALE   5000.0
5  POUSHALI   22   60000  FEMALE  12000.0
1     SNEHA   23   30000  FEMALE   6000.0
3      ABIR   22   30000    MALE   6000.0
2      SANU   22   25000    MALE   5000.0

In [185]:
# WORKING WITH DATE VALUE
df4['doj'] = ['2024-01-01', '2024-01-15' , '2024-03-28', '2024-03-23', '2024-04-27', '2024-05-13']
df4

       NANE  AGE  SALARY  GENDER   Bonous         doj
0    NILAVA   23   90000    MALE   5000.0  2024-01-01
1     SNEHA   23   30000  FEMALE   6000.0  2024-01-15
2      SANU   22   25000    MALE   5000.0  2024-03-28
3      ABIR   22   30000    MALE   6000.0  2024-03-23
5  POUSHALI   22   60000  FEMALE  12000.0  2024-04-27
6    BIDYUT   65  100000    MALE  20000.0  2024-05-13

In [186]:
df4['doj'].dtype

dtype('O')

In [187]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NANE    6 non-null      object
 1   AGE     6 non-null      int64
 2   SALARY  6 non-null      int64
 3   GENDER  6 non-null      object
 4   Bonous  6 non-null      float64
 5   doj     6 non-null      object
dtypes: float64(1), int64(2), object(3)
memory usage: 508.0+ bytes

# convert doj object to date and time

In [188]:
df4['doj'] = pd.to_datetime(df4['doj'])
# df4['doj_year'] = df4['doj'].dt.year
# df4['doj_month'] = df4['doj'].dt.month
# df4['doj_day'] = df4['doj'].dt.day

In [189]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NANE    6 non-null      object
 1   AGE     6 non-null      int64
 2   SALARY  6 non-null      int64
 3   GENDER  6 non-null      object
 4   Bonous  6 non-null      float64
 5   doj     6 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 508.0+ bytes

#extract year , month , day , dayname

In [190]:
df4['doj'].dt.year

0    2024
1    2024
2    2024
3    2024
5    2024
6    2024
Name: doj, dtype: int32

In [191]:
df5 = df4['doj'].dt.month

In [192]:
df4['doj'].dt.day

0     1
1    15
2    28
3    23
5    27
6    13
Name: doj, dtype: int32

In [193]:
df4['doj'].dt.day_name()

0      Monday
1      Monday
2    Thursday
3    Saturday
5    Saturday
6      Monday
Name: doj, dtype: object

In [194]:
df4['doj'].dt.month_name()

0    January
1    January
2      March
3      March
5      April
6        May
Name: doj, dtype: object

In [195]:
df4['doj2'] = ['01-01-2024', '01-15-2024' , '03-28-2024', '03-23-2024', '04-27-2024', '05-13-2024']
df4

       NANE  AGE  SALARY  GENDER   Bonous        doj        doj2
0    NILAVA   23   90000    MALE   5000.0 2024-01-01  01-01-2024
1     SNEHA   23   30000  FEMALE   6000.0 2024-01-15  01-15-2024
2      SANU   22   25000    MALE   5000.0 2024-03-28  03-28-2024
3      ABIR   22   30000    MALE   6000.0 2024-03-23  03-23-2024
5  POUSHALI   22   60000  FEMALE  12000.0 2024-04-27  04-27-2024
6    BIDYUT   65  100000    MALE  20000.0 2024-05-13  05-13-2024

In [196]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 6
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NANE    6 non-null      object
 1   AGE     6 non-null      int64
 2   SALARY  6 non-null      int64
 3   GENDER  6 non-null      object
 4   Bonous  6 non-null      float64
 5   doj     6 non-null      datetime64[ns]
 6   doj2    6 non-null      object
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 556.0+ bytes

In [197]:
df4['doj2'] = pd.to_datetime(df4['doj2'] , format='%m-%d-%Y')

In [198]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 6
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NANE    6 non-null      object
 1   AGE     6 non-null      int64
 2   SALARY  6 non-null      int64
 3   GENDER  6 non-null      object
 4   Bonous  6 non-null      float64
 5   doj     6 non-null      datetime64[ns]
 6   doj2    6 non-null      datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2), object(2)
memory usage: 556.0+ bytes

# add 90 days for doj

In [199]:
df4['doj2'] + pd.Timedelta(days = 90)

0   2024-03-31
1   2024-04-14
2   2024-06-26
3   2024-06-21
5   2024-07-26
6   2024-08-11
Name: doj2, dtype: datetime64[ns]

In [200]:
#handeling missing values
df4.isnull()

    NANE    AGE  SALARY  GENDER  Bonous    doj   doj2
0  False  False   False   False   False  False  False
1  False  False   False   False   False  False  False
2  False  False   False   False   False  False  False
3  False  False   False   False   False  False  False
5  False  False   False   False   False  False  False
6  False  False   False   False   False  False  False

In [201]:
# we create a nan value in salary

import numpy as np
df4.loc[df4.NANE == 'ABIR' , 'SALARY'] = np.nan

In [202]:
df4

       NANE  AGE    SALARY  GENDER   Bonous        doj       doj2
0    NILAVA   23   90000.0    MALE   5000.0 2024-01-01 2024-01-01
1     SNEHA   23   30000.0  FEMALE   6000.0 2024-01-15 2024-01-15
2      SANU   22   25000.0    MALE   5000.0 2024-03-28 2024-03-28
3      ABIR   22       NaN    MALE   6000.0 2024-03-23 2024-03-23
5  POUSHALI   22   60000.0  FEMALE  12000.0 2024-04-27 2024-04-27
6    BIDYUT   65  100000.0    MALE  20000.0 2024-05-13 2024-05-13

In [203]:
df4.isnull()

    NANE    AGE  SALARY  GENDER  Bonous    doj   doj2
0  False  False   False   False   False  False  False
1  False  False   False   False   False  False  False
2  False  False   False   False   False  False  False
3  False  False    True   False   False  False  False
5  False  False   False   False   False  False  False
6  False  False   False   False   False  False  False

In [204]:
df4.isnull().sum()

NANE      0
AGE       0
SALARY    1
GENDER    0
Bonous    0
doj       0
doj2      0
dtype: int64

In [205]:
df4.fillna(0)

       NANE  AGE    SALARY  GENDER   Bonous        doj       doj2
0    NILAVA   23   90000.0    MALE   5000.0 2024-01-01 2024-01-01
1     SNEHA   23   30000.0  FEMALE   6000.0 2024-01-15 2024-01-15
2      SANU   22   25000.0    MALE   5000.0 2024-03-28 2024-03-28
3      ABIR   22       0.0    MALE   6000.0 2024-03-23 2024-03-23
5  POUSHALI   22   60000.0  FEMALE  12000.0 2024-04-27 2024-04-27
6    BIDYUT   65  100000.0    MALE  20000.0 2024-05-13 2024-05-13

#AGGREGATION AND GROUP BY

In [206]:
df4['NANE'].value_counts()

NANE
NILAVA      1
SNEHA       1
SANU        1
ABIR        1
POUSHALI    1
BIDYUT      1
Name: count, dtype: int64

In [212]:
df4[df4['month']==1].value_counts()

NANE    AGE  SALARY   GENDER  Bonous  doj         doj2        month
NILAVA  23   90000.0  MALE    5000.0  2024-01-01  2024-01-01  1        1
SNEHA   23   30000.0  FEMALE  6000.0  2024-01-15  2024-01-15  1        1
Name: count, dtype: int64

In [210]:
df4['month'] = df4['doj'].dt.month

In [211]:
df4

       NANE  AGE    SALARY  GENDER   Bonous        doj       doj2  month
0    NILAVA   23   90000.0    MALE   5000.0 2024-01-01 2024-01-01      1
1     SNEHA   23   30000.0  FEMALE   6000.0 2024-01-15 2024-01-15      1
2      SANU   22   25000.0    MALE   5000.0 2024-03-28 2024-03-28      3
3      ABIR   22       NaN    MALE   6000.0 2024-03-23 2024-03-23      3
5  POUSHALI   22   60000.0  FEMALE  12000.0 2024-04-27 2024-04-27      4
6    BIDYUT   65  100000.0    MALE  20000.0 2024-05-13 2024-05-13      5

In [216]:
df4.groupby('month')['SALARY'].sum()

month
1    120000.0
3     25000.0
4     60000.0
5    100000.0
Name: SALARY, dtype: float64

In [221]:
from numpy._core.fromnumeric import mean
df4.groupby('month').agg({'SALARY' : 'mean' , 'NANE' : 'count'})

         SALARY  NANE
month
1       60000.0     2
3       25000.0     2
4       60000.0     1
5      100000.0     1

# CONCATINATE AND MARGE TEXT

In [222]:
d1 = pd.DataFrame({'ID' : [1 , 2 , 3] , 'NAME' : ['A' , 'B' , 'C']})
d2 = pd.DataFrame({'ID' : [1, 2 , 2, 4] , 'Score' : [800 , 40 , 60 , 50]})

In [226]:
pd.concat([d1, d2] , axis=0)

   ID NAME  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN  800.0
1   2  NaN   40.0
2   2  NaN   60.0
3   4  NaN   50.0

In [227]:
pd.concat([d1, d2] , axis=1)

    ID NAME  ID  Score
0  1.0    A   1    800
1  2.0    B   2     40
2  3.0    C   2     60
3  NaN  NaN   4     50

#marge(join)

In [229]:
pd.merge(d1 , d2 , how='inner' , on='ID')

   ID NAME  Score
0   1    A    800
1   2    B     40
2   2    B     60

In [230]:
pd.merge(d1 , d2 , how='inner' , left_on='ID' , right_on='ID')

   ID NAME  Score
0   1    A    800
1   2    B     40
2   2    B     60